### PR TITLE
handle structs only when request type is query

### PR DESCRIPTION
**Pull request by juju812**

### CODE REVIEW

**Comment by zoupengli** [comment]
this happened when using structs ptr in query params. so i think it's better to do like this:
1、 delete the handle of structs in func GetFieldValueByName of hc_http_client.go, which make this method more simply
`func (hc *HcHttpClient) GetFieldValueByName(name string, jsonTag map[string]string, structName interface{}) (reflect.Value, error) {
	v := reflect.ValueOf(structName)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	value := v.FieldByName(name)
	if value.Kind() == reflect.Ptr {
		if value.IsNil() {
			if strings.Contains(jsonTag[name], "omitempty") {
				return reflect.ValueOf(nil), nil
			}
			return reflect.ValueOf(nil), errors.New("request field " + name + " read null value")
		}
		return value.Elem(), nil
	}

	return value, nil
}`

2、 deal the struct type in func fillQueryParams in default_http_request.go like this:
`func (httpRequest *DefaultHttpRequest) fillQueryParams(req *http.Request) {
	if len(httpRequest.GetQueryParams()) == 0 {
		return
	}
	q := req.URL.Query()
	for key, value := range httpRequest.GetQueryParams() {
		if reflect.TypeOf(value).Kind() == reflect.Struct && value.(reflect.Value).Kind() == reflect.Slice {
			s := value.(reflect.Value)
			for i := 0; i < s.Len(); i++ {
				q.Add(key, fmt.Sprintf("%v", s.Index(i)))
			}
		} else if reflect.TypeOf(value).Kind() == reflect.Struct && value.(reflect.Value).Kind() == reflect.Struct {
			v, _ := jsoniter.Marshal(value.(reflect.Value).Interface())
			if strings.HasPrefix(string(v), "\"") {
				q.Add(key, strings.Trim(string(v), "\""))
			} else {
				q.Add(key, string(v))
			}
		} else {
			q.Add(key, fmt.Sprintf("%v", value))
		}
	}
	req.URL.RawQuery = q.Encode()
}`

**Comment by juju812** [comment]
@zoupengli your modification is more concise. But it need to be confirmed that if there's no other cases need to handle structs in method `GetFieldValueByName`

**Comment by zoupengli** [comment]
i will also check path params and header params

**Comment by zoupengli** [comment]
there are problems with header params. so i changed to this:
1. add func flattenEnumStruct to hc_http_client.go
```go
func flattenEnumStruct(value reflect.Value) (reflect.Value, error) {
	if value.Kind() == reflect.Struct {
		v, e := jsoniter.Marshal(value.Interface())
		if e == nil {
			if strings.HasPrefix(string(v), "\"") {
				return reflect.ValueOf(strings.Trim(string(v), "\"")), nil
			} else {
				return reflect.ValueOf(string(v)), nil
			}
		}
		return reflect.ValueOf(nil), e
	}
	return value, nil
}
```
2. change func fillParamsFromReq like this
```go
func (hc *HcHttpClient) fillParamsFromReq(req interface{}, reqDef *def.HttpRequestDef, builder *request.HttpRequestBuilder) (*request.HttpRequestBuilder, error) {
	attrMaps := hc.GetFieldJsonTags(req)

	for _, fieldDef := range reqDef.RequestFields {
		value, err := hc.GetFieldValueByName(fieldDef.Name, attrMaps, req)
		if err != nil {
			return nil, err
		}

		if !value.IsValid() {
			continue
		}

		v, err := flattenEnumStruct(value)
		if err != nil {
			return nil, err
		}

		switch fieldDef.LocationType {
		case def.Header:
			builder.AddHeaderParam(fieldDef.JsonTag, fmt.Sprintf("%v", v))
		case def.Path:
			builder.AddPathParam(fieldDef.JsonTag, fmt.Sprintf("%v", v))
		case def.Query:
			builder.AddQueryParam(fieldDef.JsonTag, v)
		case def.Body:
			builder.WithBody(value.Interface())
		}
	}
	return builder, nil
}
```

**Comment by juju812** [comment]
seems like method `flattenEnumStruct` has to be moved into QueryParam, like what I did, otherwise there will be problem in Body

**Pull request closed without merging**
